### ISSUE TITLE
Crash on 3.1

### ISSUE THREAD

**Issue by CrazyWolf13** [jbcarreon123/WebNowPlaying-Redux-Macro-Deck#10]
Macrodeck is crashing and launching in safe mode after installing version 3.10

**Comment by jbcarreon123** [comment]
Can you show the logs? Are you running 2.13.0?

**Comment by CrazyWolf13** [comment]
> Can you show the logs? Are you running 2.13.0?

After downloading the zip and importing in macrodeck I get this message:
![image](https://github.com/jbcarreon123/WebNowPlaying-Redux-Macro-Deck/assets/96661824/dd61f950-374b-4e38-9eb7-52c485d291c8)

**Comment by CrazyWolf13** [comment]
[2023-08-22.log](https://github.com/jbcarreon123/WebNowPlaying-Redux-Macro-Deck/files/12411559/2023-08-22.log)

**Comment by jbcarreon123** [comment]
> > Can you show the logs? Are you running 2.13.0?
> 
> After downloading the zip and importing in macrodeck I get this message: ![image](https://user-images.githubusercontent.com/96661824/262442077-dd61f950-374b-4e38-9eb7-52c485d291c8.png)

That means you are using 2.12. the latest version is only compatible with 2.13.0b1.

**Comment by CrazyWolf13** [comment]
> > > Can you show the logs? Are you running 2.13.0?
> > 
> > After downloading the zip and importing in macrodeck I get this message: ![image](https://user-images.githubusercontent.com/96661824/262442077-dd61f950-374b-4e38-9eb7-52c485d291c8.png)
> 
> That means you are using 2.12. the latest version is only compatible with 2.13.0b1.

And that is referred to what?
Macrodeck?
So it's only for beta release?

**Comment by jbcarreon123** [comment]
> > > > Can you show the logs? Are you running 2.13.0?
> > > 
> > > 
> > > After downloading the zip and importing in macrodeck I get this message: ![image](https://user-images.githubusercontent.com/96661824/262442077-dd61f950-374b-4e38-9eb7-52c485d291c8.png)
> > 
> > 
> > That means you are using 2.12. the latest version is only compatible with 2.13.0b1.
> 
> And that is referred to what? Macrodeck? So it's only for beta release?

Yes. The latest version only supports 2.13.0 and up.

**Comment by CrazyWolf13** [comment]
> > > > > Can you show the logs? Are you running 2.13.0?
> > > > 
> > > > 
> > > > After downloading the zip and importing in macrodeck I get this message: ![image](https://user-images.githubusercontent.com/96661824/262442077-dd61f950-374b-4e38-9eb7-52c485d291c8.png)
> > > 
> > > 
> > > That means you are using 2.12. the latest version is only compatible with 2.13.0b1.
> > 
> > 
> > And that is referred to what? Macrodeck? So it's only for beta release?
> 
> Yes. The latest version only supports 2.13.0 and up.

Oh, I'm really sorry, I coulnd't find that anywhere. 
Sorry for that issue report:/

**Comment by jbcarreon123** [comment]
Yeah, that's okay.
